'use client'

import React, { useState } from 'react'
import { toast } from 'sonner'
import {
  CheckCircle2,
  X,
  RefreshCw,
  Calendar,
  Loader2,
  Sparkles,
  Coins,
  Send,
  Eye,
  SlidersHorizontal,
  FileEdit,
  Clock,
  Check,
} from 'lucide-react'

import { PageHeader } from '@/components/reusable/PageHeader'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Textarea } from '@/components/ui/textArea'
import { NoDataFound } from '@/components/reusable/NoDataFound'
import {
  useGetContentCalendarQuery,
  useUpdateContentStatusMutation,
  useScheduleContentMutation,
  useGenerateCaptionMutation,
  useGetBusinessProfileQuery,
} from '@/redux/api/aiSocialApi'
import { useRouter } from 'next/navigation'

const STATUS_FILTERS = [
  { id: 'All', label: 'All Items' },
  { id: 'Owner_Review', label: 'Needs Review' },
  { id: 'Approved', label: 'Approved' },
  { id: 'Scheduled', label: 'Scheduled' },
  { id: 'Published', label: 'Published' },
  { id: 'Draft', label: 'Drafts' },
]

const PLATFORM_ICONS: Record<string, string> = {
  Instagram: '📸 Instagram',
  Facebook: '📘 Facebook',
  LinkedIn: '💼 LinkedIn',
  YouTube: '▶️ YouTube',
  GoogleBusinessProfile: '📍 Google Business',
}

const STATUS_BADGE_VARIANTS: Record<string, 'default' | 'secondary' | 'destructive' | 'outline' | 'premium' | 'glass'> = {
  Draft: 'outline',
  AI_Review: 'secondary',
  Owner_Review: 'premium',
  Approved: 'default',
  Scheduled: 'glass',
  Published: 'default',
  Failed: 'destructive',
}

const MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
]

export default function ApprovalCenterPage() {
  const router = useRouter()
  const now = new Date()
  const [month, setMonth] = useState(MONTHS[now.getMonth()])
  const [year, setYear] = useState(now.getFullYear())
  const [filter, setFilter] = useState('Owner_Review')
  const [expandedId, setExpandedId] = useState<string | null>(null)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [editCaptionText, setEditCaptionText] = useState('')

  const { data: profileData } = useGetBusinessProfileQuery(undefined)
  const business = (profileData as any)?.data
  const { data, isLoading, refetch } = useGetContentCalendarQuery(
    { businessId: business?._id, month, year },
    { skip: !business?._id }
  )

  const [updateStatus] = useUpdateContentStatusMutation()
  const [scheduleContent, { isLoading: scheduling }] = useScheduleContentMutation()
  const [generateCaption, { isLoading: generatingCaption }] = useGenerateCaptionMutation()

  const items: any[] = (data as any)?.data?.items || []
  const filtered = filter === 'All' ? items : items.filter((i: any) => i.status === filter)

  const approve = async (item: any) => {
    try {
      await updateStatus({ id: item._id, status: 'Approved' }).unwrap()
      toast.success('Approved!')
    } catch {
      toast.error('Failed to approve')
    }
  }

  const approveAndSchedule = async (item: any) => {
    try {
      await updateStatus({ id: item._id, status: 'Approved' }).unwrap()
      await scheduleContent(item._id).unwrap()
      toast.success('Approved and queued for n8n execution!')
    } catch {
      toast.error('Scheduling failed')
    }
  }

  const reject = async (item: any) => {
    try {
      await updateStatus({ id: item._id, status: 'Draft', rejectionNote: 'Needs manual revision' }).unwrap()
      toast.info('Sent back to draft for adjustments')
    } catch {
      toast.error('Failed to reject')
    }
  }

  const regen = async (item: any) => {
    try {
      await generateCaption({ contentItemId: item._id }).unwrap()
      toast.success('New hook & caption generated by AI!')
      refetch()
    } catch {
      toast.error('Regeneration failed')
    }
  }

  return (
    <div className="space-y-6 max-w-6xl mx-auto p-2 sm:p-4">
      <PageHeader
        title="Content Approval Center"
        showBackButton={true}
        endContent={
          <div className="flex items-center gap-2">
            <select
              value={month}
              onChange={(e) => setMonth(e.target.value)}
              className="h-10 rounded-[8px] border border-input-border-color bg-background px-3 text-sm focus:outline-none text-foreground inner-card"
            >
              {MONTHS.map((m) => (
                <option key={m} value={m}>{m}</option>
              ))}
            </select>
          </div>
        }
      />

      {/* Filter Tabs */}
      <div className="flex gap-2 overflow-x-auto pb-1 scrollbar-none">
        {STATUS_FILTERS.map((s) => {
          const count = s.id === 'All' ? items.length : items.filter((i: any) => i.status === s.id).length
          const isSelected = filter === s.id
          return (
            <Button
              key={s.id}
              variant={isSelected ? 'premium' : 'outline'}
              size="sm"
              onClick={() => setFilter(s.id)}
              className="rounded-full gap-2 text-xs"
            >
              {s.label}
              <Badge variant={isSelected ? 'glass' : 'secondary'} className="px-1.5 py-0 text-[10px] font-bold">
                {count}
              </Badge>
            </Button>
          )
        })}
      </div>

      {isLoading && (
        <div className="flex items-center justify-center py-20">
          <Loader2 className="w-8 h-8 animate-spin text-primary" />
        </div>
      )}

      {!isLoading && !business && (
        <Card className="border border-border text-center py-12 p-6">
          <CardContent className="space-y-4">
            <Sparkles className="w-10 h-10 text-primary mx-auto" />
            <h3 className="text-lg font-bold text-foreground">Business Brain Required</h3>
            <p className="text-sm text-muted-foreground max-w-md mx-auto">
              Please complete your business profile setup so the AI engine has brand details to review against.
            </p>
            <Button variant="premium" onClick={() => router.push('/ai-social/setup')}>
              Complete Setup
            </Button>
          </CardContent>
        </Card>
      )}

      {!isLoading && business && filtered.length === 0 && (
        <Card className="border border-border text-center py-12 p-6">
          <CardContent className="space-y-3">
            <CheckCircle2 className="w-10 h-10 text-primary/40 mx-auto" />
            <h3 className="text-base font-semibold">No content in this review queue</h3>
            <p className="text-xs text-muted-foreground">
              All caught up, or no posts match the selected filter.
            </p>
            <Button variant="outline" size="sm" onClick={() => setFilter('All')}>
              View All Content
            </Button>
          </CardContent>
        </Card>
      )}

      {/* Content Cards Grid */}
      <div className="grid gap-4">
        {filtered.map((item: any) => {
          const isExpanded = expandedId === item._id
          return (
            <Card key={item._id} className="border border-border transition-all duration-200 hover:border-primary/40">
              <CardContent className="p-5 flex flex-col md:flex-row items-start gap-4">
                {/* Media thumbnail or platform placeholder */}
                <div className="w-20 h-20 rounded-xl bg-muted border border-border flex items-center justify-center shrink-0 overflow-hidden">
                  {item.creativeUrl ? (
                    <img src={item.creativeUrl} alt="creative preview" className="w-full h-full object-cover" />
                  ) : (
                    <span className="text-2xl">📱</span>
                  )}
                </div>

                {/* Main Content Details */}
                <div className="flex-1 min-w-0 space-y-1.5">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="text-xs font-semibold text-muted-foreground">
                      {PLATFORM_ICONS[item.platform] || item.platform}
                    </span>
                    <Badge variant={STATUS_BADGE_VARIANTS[item.status] || 'secondary'} className="text-[11px]">
                      {item.status.replace('_', ' ')}
                    </Badge>
                    {item.format && <Badge variant="outline" className="text-[10px]">{item.format}</Badge>}
                    {item.contentType && <Badge variant="outline" className="text-[10px]">{item.contentType}</Badge>}
                  </div>

                  <h4 className="font-bold text-sm text-foreground leading-snug">{item.topic}</h4>

                  {item.hook && (
                    <p className="text-xs text-primary font-medium italic">
                      Hook: "{item.hook}"
                    </p>
                  )}

                  {item.caption && (
                    <p className="text-xs text-muted-foreground line-clamp-2 leading-relaxed">
                      {item.caption}
                    </p>
                  )}

                  <div className="flex flex-wrap items-center gap-4 text-xs text-muted-foreground pt-1">
                    {item.publishDate && (
                      <span className="flex items-center gap-1">
                        <Calendar className="w-3.5 h-3.5" />
                        {new Date(item.publishDate).toLocaleDateString()}
                      </span>
                    )}
                    {item.creditsUsed > 0 && (
                      <span className="flex items-center gap-1 font-semibold text-foreground">
                        <Coins className="w-3.5 h-3.5 text-amber-500" />
                        {item.creditsUsed} credits used
                      </span>
                    )}
                  </div>
                </div>

                {/* Actions */}
                <div className="flex flex-row md:flex-col gap-2 shrink-0 w-full md:w-auto justify-end pt-2 md:pt-0">
                  {(item.status === 'Owner_Review' || item.status === 'AI_Review') && (
                    <>
                      <Button
                        variant="premium"
                        size="sm"
                        disabled={scheduling}
                        onClick={() => approveAndSchedule(item)}
                        className="gap-1.5 text-xs h-9"
                      >
                        {scheduling ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Send className="w-3.5 h-3.5" />}
                        Approve & Schedule
                      </Button>

                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => approve(item)}
                        className="gap-1.5 text-xs h-9"
                      >
                        <Check className="w-3.5 h-3.5 text-emerald-500" />
                        Approve Only
                      </Button>

                      <div className="flex gap-2">
                        <Button
                          variant="ghost"
                          size="sm"
                          disabled={generatingCaption}
                          onClick={() => regen(item)}
                          className="text-xs h-8 flex-1 text-primary hover:bg-primary/10"
                        >
                          <RefreshCw className="w-3.5 h-3.5 mr-1" />
                          Regen
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => reject(item)}
                          className="text-xs h-8 flex-1 text-destructive hover:bg-destructive/10"
                        >
                          <X className="w-3.5 h-3.5 mr-1" />
                          Reject
                        </Button>
                      </div>
                    </>
                  )}

                  {item.status === 'Approved' && (
                    <Button
                      variant="premium"
                      size="sm"
                      disabled={scheduling}
                      onClick={() => scheduleContent(item._id)}
                      className="gap-1.5 text-xs h-9"
                    >
                      <Clock className="w-3.5 h-3.5" />
                      Queue to n8n
                    </Button>
                  )}
                </div>
              </CardContent>

              {/* Full Caption Expandable Section */}
              {item.caption && (
                <div className="border-t border-border/40 px-5 py-3 bg-muted/20">
                  <button
                    onClick={() => setExpandedId(isExpanded ? null : item._id)}
                    className="text-xs font-semibold text-primary hover:underline flex items-center gap-1"
                  >
                    {isExpanded ? 'Hide Full Content Details ▲' : 'View Full Caption, CTA & Hashtags ▼'}
                  </button>

                  {isExpanded && (
                    <div className="mt-3 space-y-3 pt-2 border-t border-border/40 text-xs">
                      <div className="space-y-1">
                        <span className="font-bold text-foreground">Post Text:</span>
                        <p className="whitespace-pre-wrap text-muted-foreground leading-relaxed bg-background p-3 rounded-lg border border-border">
                          {item.caption}
                        </p>
                      </div>

                      {item.cta && (
                        <div className="flex items-center gap-2">
                          <span className="font-bold text-foreground">Call to Action:</span>
                          <Badge variant="outline" className="text-primary font-medium">{item.cta}</Badge>
                        </div>
                      )}

                      {item.hashtags?.length > 0 && (
                        <div className="flex flex-wrap gap-1.5 pt-1">
                          {item.hashtags.map((h: string) => (
                            <span key={h} className="text-primary font-mono text-[11px] bg-primary/10 px-2 py-0.5 rounded">
                              #{h}
                            </span>
                          ))}
                        </div>
                      )}
                    </div>
                  )}
                </div>
              )}
            </Card>
          )
        })}
      </div>
    </div>
  )
}
