export const ROUTES = {
  AUTH: {
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    VERIFY_OTP: '/verify-otp',
    RESET_PASSWORD: '/reset-password',
  },
  DASHBOARD: '/dashboard',
  MCP: '/mcp-studio',
  MCP_STUDIO: '/mcp-studio',
  CHAT_ASSISTANT: {
    LIST: '/ai-chat-assistant',
    GPT4: '/ai-chat-assistant/gpt4',
    CLAUDE: '/ai-chat-assistant/claude',
    LIVE_AGENT: '/ai-live-agent',
  },
  CHATBOT_BUILDER: '/ai-bot-studio',
  CONTENT_WRITER: '/ai-blog-writer',
  CODE_ASSISTANT: '/ai-codex',
  CODE_ASSISTANT_HISTORY: '/ai-codex/history',
  DETECT_AI: '/ai-detect',
  SMART_WRITER: '/ai-writing-assistant',
  SMART_WRITER_HISTORY: '/ai-writing-assistant/history',
  CONTENT_REWRITER: '/ai-content-rewriter',
  CONTENT_REWRITER_HISTORY: '/ai-content-rewriter/history',
  SLIDE_MAKER: '/ai-slide-maker',
  SLIDE_MAKER_HISTORY: '/ai-slide-maker/history',
  AI_AVATAR: '/ai-avatar',
  AI_AVATAR_HISTORY: '/ai-avatar/history',
  AI_TRANSCRIPTION: '/ai-transcription',
  SMART_FILE_CHAT: '/ai-file-bot',
  MEMBERS: '/members',
  PERMISSIONS: '/permissions',
  PLANS: '/plans',
  LANGUAGES: '/languages',
  CONTACTS: {
    HOME: '/contacts',
    LIST: '/contact-group',
    AUDIENCE: '/audience',
  },
  SUBSCRIPTIONS: '/subscriptions',
  TRANSACTIONS: '/transactions',
  APP_SETTINGS: {
    HOME: '/app-settings',
    API_KEYS: '/api-keys',
    MCP: '/mcp',
    WEB_PAGES: '/web-pages',
    PAYMENT_SETUP: '/payment-setup',
  },
  SUPPORT: {
    KNOWLEDGE_BASE: '/support/knowledge-base',
  },
  INQUIRIES: '/inquiries',
  FAQS: '/faqs',
  CAMPAIGNS: {
    HOME: '/campaigns',
    CREATE: '/campaigns/create',
    MAIL_SETUP: '/mail-setup',
  },
  SOCIAL_MEDIA: {
    ADS_MANAGER: '/social-media/ads-manager',
    TIKTOK_ADS: '/social-media/tiktok-ads',
    REDDIT_ADS: '/social-media/reddit-ads',
    GOOGLE_ADS: '/social-media/google-ads',
    DASHBOARD: '/social-media/dashboard',
    CHANNELS: '/social-media/channels',
    CALENDAR: '/social-media/calendar',
    POST_QUEUE: '/social-media/post-queue',
    LOGS: '/social-media/logs',
    CREATE_POST: '/social-media/create-post',
    ANALYTICS: '/social-media/analytics',
    SOCIAL_SETTINGS: '/social-media/social-settings',
    CAMPAIGN: '/social-media/campaign',
    PLATFORMS: '/social-media/channels',
  },
  PROFILE: '/profile',
  CAMPAIGN_HUB: {
    CAMPAIGN_HUB: '/campaign-hub/dashboard',
    MESSAGES: '/campaign-hub/messages',
    BROADCASTS: {
      HOME: '/campaign-hub/broadcasts',
      EMAIL: '/campaign-hub/broadcasts/email',
      WHATSAPP: '/campaign-hub/broadcasts/whatsapp',
      TELEGRAM: '/campaign-hub/broadcasts/telegram',
      CREATE: {
        EMAIL: '/campaign-hub/broadcasts/email/create',
        WHATSAPP: '/campaign-hub/broadcasts/whatsapp/create',
        TELEGRAM: '/campaign-hub/broadcasts/telegram/create',
      },
    },
    CONTACTS: {
      HOME: '/campaign-hub/contacts',
      LIST: '/campaign-hub/contact-group',
      AUDIENCE: '/campaign-hub/audience',
    },
    TELEGRAM: {
      HOME: '/campaign-hub/telegram',
      GROUPS: '/campaign-hub/telegram/groups',
      SUBSCRIBERS: '/campaign-hub/telegram/subscribers',
    },
    WHATSAPP: '/campaign-hub/whatsapp',
    SETTINGS: {
      HOME: '/campaign-hub/settings',
      MAIL_SETUP: '/campaign-hub/settings/mail-setup',
      BOT_PREFERENCES: '/campaign-hub/settings/bot-preferences',
    },
  },
  AI_SOCIAL: {
    SETUP: '/ai-social/setup',
    PLANNER: '/ai-social/planner',
    TEMPLATES: '/ai-social/templates',
    CALENDAR: '/ai-social/calendar',
    APPROVAL: '/ai-social/approval',
    ANALYTICS: '/ai-social/analytics',
    CREDITS: '/ai-social/credits',
    INDIAN_FESTIVALS: '/ai-social/indian-festivals',
    ADMIN_TEMPLATES: '/ai-social/admin/templates',
    ADMIN_CREDITS: '/ai-social/admin/credits',
  },
  AI_EMPLOYEES: {
    ONBOARDING: '/ai-employees/onboarding',
    DASHBOARD: '/ai-employees/dashboard',
    WEBSITE_BUILDER: '/ai-employees/website-builder',
    SEO_AGENT: '/ai-employees/seo-agent',
    SERVER_AGENT: '/ai-employees/server-agent',
    MAINTENANCE_AGENT: '/ai-employees/maintenance-agent',
    SOCIAL_AGENT: '/ai-employees/social-agent',
    GOOGLE_BUSINESS: '/ai-employees/google-business',
    CREDITS: '/ai-employees/credits',
  },
  HOME: '/',
} as const
